development:
  adapter: postgresql
  encoding: unicode
  database: BanquetManager_development
  pool: 5
  username: dom 
  password: <%= ENV["PG_PASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: BanquetManager_test
  pool: 5
  username: dom
  password: <%= ENV["PG_PASSWORD"] %>

production:
  adapter: postgresql
  encoding: unicode
  database: BanquetManager_production
  pool: 5
  username: BanquetManager
  password: <%= ENV["PG_PASSWORD"] %>
